### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by jaapterwoerds** [prathyvsh/morphisms-of-computational-structures#51]
In absence of a messaging systems in Github, I want to thank you for putting in the time and effort and making this publically available.

**Comment by prathyvsh** [comment]
Hey there,

Thanks for the kind words! Where did you learn about this?

Because it's somewhat heavily WIP at the moment, I haven't publicized it in many places.

Cheers,
Prathyush

**Comment by jaapterwoerds** [comment]
I can't remember exactly, but I probably got it from twitter from peeps in my category theory / PL filter bubble. My personal interest are, among others, (the history of) theoretical computer science, logic, philosophy and foundation of mathematics, category theory. 

Thanks for the write up and keep up!

**Comment by prathyvsh** [comment]
@jaapterwoerds Cool, to know man. And thanks for the kind words. Hope to make this into a more cogent piece. Still trying to piece different parts of the story myself. Will do my best.

Thanks again,
Prathyush
